[tool.poetry]
name = "rich-tables"
version = "0.1.0"
description = "Ready-made rich tables for various purposes"
authors = ["Šarūnas Nejus <snejus@protonmail.com>"]
packages = [{ from = "src", include = "rich_tables" }]

[tool.poetry.dependencies]
python = ">=3.7,<4"

rich = ">=12.3.0"
python-dateutil = ">=2.8.2"
rgbxy = ">=0.5"
ordered-set = ">=4.0.2"
pycountry = ">=20.7.3"
pytest-clarity = "^1.0.1"

[tool.poetry.group.dev.dependencies]
flake8 = ">=4.0.1"
mypy = ">=0.910"
pylint = ">=2.13.7"

pytest = ">=7.1.2"
pytest-cov = ">=3.0.0"
freezegun = ">=1.2.1"

PyGObject = ">=3.42.1"
types-six = ">=1.16.2"
types-python-dateutil = ">=2.8.3"
types-freezegun = "^1.1.9"

[tool.poetry.scripts]
table = "rich_tables.table:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
