---
name: Code quality
on:
  push
jobs:
  test:
    env:
      python: "3.9"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Generate requirements.txt
        run: 
          ./generate_requirements > requirements.txt
          echo coveralls >> requirements.txt
      - name: Set up Python ${{ env.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python }}
          cache: pip
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -e .
      - name: Pytest
        run: pytest
      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: python${{ env.python }}
          COVERALLS_PARALLEL: true
      - name: Flake8
        run: flake8 . --output-file flake.log --exit-zero
      - name: Pylint
        run: pylint --output pylint.log --exit-zero $(git ls-files '*.py')
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  coveralls:
    if: ${{ always() }}
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
