---
name: Code quality
on: push
jobs:
  test:
    env:
      python: "3.9"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up Python ${{ env.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python }}

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Pytest
        run: poetry run pytest -vv

      - name: Upload coverage data to coveralls.io
        run: |
          poetry run coveralls --service=github

      - name: Flake8
        run: poetry run flake8 . --output-file flake.log --exit-zero --mypy-config setup.cfg

      - name: Pylint
        run: poetry run pylint --output pylint.log --exit-zero $(git ls-files '*.py')

      - name: Set project version
        run: echo PROJECT_VERSION="$(git describe | sed 's/-[^-]*$//')" >> $GITHUB_ENV

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=snejus
            -Dsonar.projectKey=snejus_rich-tables
            -Dsonar.projectVersion=${{ env.PROJECT_VERSION }}
            -Dsonar.python.coverage.reportPaths=.reports/coverage.xml
            -Dsonar.python.version=3.9
            -Dsonar.python.xunit.reportPath=./pytest-main.xml
            -Dsonar.python.flake8.reportPaths=flake.log
            -Dsonar.python.pylint.reportPaths=pylint.log
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.test.inclusions=tests/**/*
            -Dsonar.exclusions=tests/**/*
